version: '3.8'

services:
  db:
    container_name: data-filme
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: filmes
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - C:/Users/Dicya/projetos/mysql-data:/var/lib/mysql

  app:
    container_name: filme-unifacisa-backend
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://data-filme:3306/filmes
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge