version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: filmes
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"


  app:
    image: dicyane/filme-unifacisa-back:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/filmes
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db


